### ISSUE TITLE
Code retention check

### ISSUE THREAD

**Issue by MatisseBE** [kusterjs/CCAMS#1]
Hi!

Would it be possible to add an extra squawk code retention error indicator to the plugin? 

The plugin would check if a modeS squawk has been falsely (not capable, not fully through modeS area) given by a controller not using the plugin. In EBBU airspace we are required to change transponders with squawk 1000 going to London (misuse of modeS). For us, they are well correlated and thus we don't notice anything wrong with the track, however for London these aircraft are not correlated and this creates issues.

An error indicator, similar to the well known DUPE error, would allow us to notice misusue and reclycle to a new, valid squawk.

Obviously such error would not exist in real live as squawks are centrally managed by Eurocontrol, and most importantly, because everyone uses said system. Therefore, you could reuse the DUPE error to maintain a certain level of realism or create a different error indicator to easily distinguish the two.

**Comment by kusterjs** [comment]
Thanks for the proposal. Will make an addition for the next version.

**Comment by kusterjs** [comment]
Tested, will be implemented in v1.7
