### ISSUE TITLE
Feature request: assign SSRs with F9

### ISSUE THREAD

**Issue by javoescan** [kusterjs/CCAMS#10]
Euroscope currently supports assigning squawks with F9. It places the ".QB" command on the command line and you can either manually input a squawk, or if you just hit enter it will auto assign a squawk according to the range set in the general settings.

Link to documentation; https://www.euroscope.hu/wp/editing-and-function-keys/

**Comment by kusterjs** [comment]
The plugin interface offered does currently not support that. I'm therefore unable to implement such a functionality.
