### ISSUE TITLE
Bug: incorrect squawks generation for SACF

### ISSUE THREAD

**Issue by javoescan** [kusterjs/CCAMS#11]
**Description**: Incorrect squawks generation for SACF

**Position**: SACO_APP

**Actual behavior**
- For a SACO/SABE flight, it generated 2104
- For a SACO/SLVR flight, it generated 0607

**Expected behavior**
- For a SACO/SABE flight, it should generate squawks between 2001/2047
- For a SACO/SLVR flight, it should generate squawks between 2500/2577

**Version**: 1.7.0

**Extra information**
The SSRs that its generating right now are from SARR, maybe there was a confusion while setting the ranges?

**Comment by kusterjs** [comment]
Please provide the date when this behaviour was observed.

**Comment by javoescan** [comment]
All "incorect squawks generations" bug were tested yesterdar 6/5/2021 at 3PM UTC

**Comment by kusterjs** [comment]
Referring to https://ccams.kilojuliett.ch/ and #2, can you verify than once again the SSR code ranges for each FIR designator?

**Comment by javoescan** [comment]
@kusterjs I can confirm that on https://ccams.kilojuliett.ch/ the three FIRs (SARR, SAMF and SACF) have their ranges wrong and they don't match with the image posted on https://github.com/kusterjs/CCAMS/issues/2.

**Comment by javoescan** [comment]
I can write them down separately if that works for you

**Comment by kusterjs** [comment]
I just need to know which names from the graphic belong to which designators.

**Comment by javoescan** [comment]
FIR Ezeiza -> SAEF
FIR Comodoro -> SAVC
FIR Cordoba -> SACF
FIR Resistencia -> SARR
FIR Mendoza -> SAMF

**Comment by kusterjs** [comment]
Comodoro is SAVC or SAVF?

**Comment by javoescan** [comment]
Sorry, SAVF

**Comment by kusterjs** [comment]
FIR ranges changed as requested
