### ISSUE TITLE
Feature request: international arriving traffic

### ISSUE THREAD

**Issue by javoescan** [kusterjs/CCAMS#14]
Right now, CCAMS would generate a completely random squawk for an international arriving traffic since it doesn't match with any of the provided ranges.

It would be great to select a squawk from the arriving FIR's international range.

Non show stopper at all!

**Comment by kusterjs** [comment]
What controller call sign was involved?

**Comment by javoescan** [comment]
It was BAIRES_CTR

**Comment by kusterjs** [comment]
Ok. There is no obvious relation of this call sign to an FIR designator, hence a random squawk is used. What is the code range of this station? Is there a relation to any FIR?

**Comment by javoescan** [comment]
BAIRES_CTR is the approach controller for SAEZ, SABE and other minor airports. It's within SAEF FIR, so same SSRs rules apply for this position.
Just because this came up now, should I send you a list of airports for each FIR? Or it's not needed?

**Comment by kusterjs** [comment]
I only need information for those positions not using an ICAO designator or missing a connection to a specific FIR in the VatSPY database.

**Comment by javoescan** [comment]
Oh okay, then we should be fine. I think in VATSpy's database there might be some deprecated positions but I can take a look into it

**Comment by kusterjs** [comment]
BAIRES added to FIR list
