### ISSUE TITLE
Support CCAMS on Argentina

### ISSUE THREAD

**Issue by javoescan** [kusterjs/CCAMS#2]
Hey Jonas! Thank you for your amazing work with CCAMS.
We are looking to extend it so it works with our rules of transponders. Those are:

- Range per FIR (we have 5 of them)
- Range per type of flight (national, international or VFR)

It would be something like this:
![image](https://user-images.githubusercontent.com/18704732/114245241-798e1280-9966-11eb-8af8-ecdefaa162d8.png)

Even if it requires some coding, what are your thoughts on this? How could we manage to implement that logic to generate a ssr that correctly corresponds to the flight?

Thank you so much in advance!

**Comment by kusterjs** [comment]
I'll definitely will have a look at this. Can you let me know the ICAO designators of those FIRs? When I'll try step by step to extend the logic.

**Comment by javoescan** [comment]
Sure! They are:
SAEF, SAMF, SARR, SACF and SAVF.

National means it will stay within Argentinian airspace (any airport starting with SA or aerodromes without ICAO code).

Please, don't feel that you need to do the development for us! We are happy to help there if needed.
Since we were in a rush we went with TopSky to get it up and running ASAP but we are excited about CCAMS so let us know whatever we can do to help with the project.

Thank you so much!
Best regards

**Comment by kusterjs** [comment]
No worries. Am up for the challenge, and I also expect similar customisation requests from other regions in the future. This needs to be implemented on the server side anyway to keep the centralised distribution principle.

The FIR codes are added and any controller using them in their call sign should now be able to assign the "international" squawks. I'm still working on the national ones and VFR ones.

**Comment by javoescan** [comment]
Great. Thank you!

**Comment by kusterjs** [comment]
National and VFR codes are now implemented server-side. The plugin version 1.7.0 is already sufficient. Please test and let me know if the assigned codes are according your request.

**Comment by javoescan** [comment]
@kusterjs amazing, thank you so much! I'll take a look into it as soon as I can

**Comment by javoescan** [comment]
@kusterjs hey! Sorry for the long delay, it's been busy days here. I'm trying to install the plugin but I can't find the dll file, am I missing something? Also, I'm more than ok to follow up this offline and close the issue since is technically done. Thank you so much for you hard work!

**Comment by kusterjs** [comment]
Ok thanks. Than I'll close the issue.
The instruction for the plugin use can be found in the readme.
