### ISSUE TITLE
Exclude airports from Mode-S assignment

### ISSUE THREAD

**Issue by laxentis** [kusterjs/CCAMS#23]
Can we exclude an airport in FIR from being mode S capable?
Our military fields do not support mode S (yet, and are not planned in near future) so any flight going to EPCE, EPDA, EPDE, EPIR, EPKS, EPLK, EPLY, EPMB, EPMI, EPMM, EPOK, EPPR, EPPW, EPSN, EPTM should be given discrete SSR.
Our FIR is included as per #15

**Comment by kusterjs** [comment]
No, exclusion is not possible. You can only include less. Because by default, an airport is not considered mode S capable. Mode S capable regions are listed in the [ver.txt](https://raw.githubusercontent.com/kusterjs/CCAMS/master/CCAMS/ver.txt) file according the readme file.
As it lists currently "EP", any airport starting with EP will be considered mode S capable. But this entry can be changed and replaced by groups (EPW*) or single airports. For this I would require a list of airports, which **are** mode S capable. So not the ones that are not.

The ranges for discrete squawk codes you mentioned with #15 are not related to the mode S capability.

**Comment by laxentis** [comment]
So... maybe other way round.
Is it  possible to have another function in the menu to assign a discrete code no matter the Mode-S status of the flight (just like we assign VFR codes)?

**Comment by laxentis** [comment]
Sorry, accidentally closed.

**Comment by kusterjs** [comment]
> So... maybe other way round. Is it possible to have another function in the menu to assign a discrete code no matter the Mode-S status of the flight (just like we assign VFR codes)?
Yes exactly, it works the other way round.
Why would you require still a discrete code to be assigned even if Mode S is checked to be applicable? That's kind of circumnavigating the plugins intentions, which is not necessary if the configuration is done correctly. It also might lead to different controllers using mode S or not. And I don't see a reason why this should be the case.

**Comment by kusterjs** [comment]
> > So... maybe other way round. Is it possible to have another function in the menu to assign a discrete code no matter the Mode-S status of the flight (just like we assign VFR codes)?
> 
> Yes exactly, it works the other way round. Why would you require still a discrete code to be assigned even if Mode S is checked to be applicable? That's kind of circumnavigating the plugins intentions, which is not necessary if the configuration is done correctly. It also might lead to different controllers using mode S or not. And I don't see a reason why this should be the case.

@laxentis Still curious for your answer.

And regarding your original request: if you provide me a list of airports which **are** mode S capable, I'm happy to change the configuration accordingly.

**Comment by laxentis** [comment]
Sorry for the delay.
I was thinking if it was even worth making a change. We have literally one airport that sees Mode S capable aircraft, but the ATS is not Mode S capable itself. It sees so little traffic on Vatsim that I don't think there is a need.

**Comment by kusterjs** [comment]
Ok. Thanks for the feedback. And if you change your mind, just open a new issue. I only would need a list of all airports which are Mode S capable.
