### ISSUE TITLE
Request squawk failed

### ISSUE THREAD

**Issue by Iwhite67** [kusterjs/CCAMS#26]
Hello,

From yesterday, problem when french ATC requesting a squawk code

On website, only NIL
https://ccams.kilojuliett.ch/

![unknown-2.png](https://user-images.githubusercontent.com/9698964/145851225-a0e81ff3-0b23-45c8-ab46-e32fbaa19768.png)

**Comment by kusterjs** [comment]
Please report the login call sign and your plugin version.

**Comment by Iwhite67** [comment]
1.7.2
All aircraft who don't get 1000

I will request some callsign

**Comment by kusterjs** [comment]
ok, seems there was a minor issue on the server backend. It's fixed now. Please open a new issue if the problem returns.
