### ISSUE TITLE
Accept/Assign code 1000 if a flight remains within Mode S Area for the remainder of the flight

### ISSUE THREAD

**Issue by erikwachters** [kusterjs/CCAMS#28]
Hello,
I tested the new version yesterday but it doesn't seem to work as it should.
I controled the EBBU EAST sectors so I was completely surrounded by ModeS 1000 area. Every time I got a flight which didn't leave in a sq1000 area from one of the neighbors I got an MSSQ warning to set a local SQ. Actually, this was not necessary as the 1000 had already been given by an upstream sector that knew that the flight from him would turn out to be in 1000 area.
ex: flight KJFK to ELLX. The flight departed NON SQ1000 area but a 1000 was assigned by EBBU WEST (which is sq1000 area). When the flight came with me I got the MSSQ warning to set a local SQ altough the flight was never to leave SQ1000 area again.
Normal behaviour should be that if the flight has 1000 and it comes from and goes to SQ1000 area, it should keep 1000.

Thank you for the great work!

E.

**Comment by kusterjs** [comment]
Thanks Erik for your feedback. The behaviour is actually intended the way you described it. But I see it doesn't make sense and results in many unnecessary discrete code assignments. I'll change it.

**Comment by kusterjs** [comment]
Contrary to my initial reply, code 1000 will not be replaced if the flight is in a sector that has mode S capability, and its destination is able mode S as well. I'm aware of issues though where the aircraft equipment information is removed, and the CCAMS plugin therefore needs to assume that this aircraft is not mode S capable. Then, of course a discrete code is assigned.
If you observe again these cases, can you provide a screenshot or textual information of the full flight plan (ES native mask, or text from the VATSIM stats page)?

**Comment by erikwachters** [comment]
I don't know what you mean with "ES native mask".
The previous version worked perfectly so it must be something that is changed in the new version.

**Comment by kusterjs** [comment]
> I don't know what you mean with "ES native mask". The previous version worked perfectly so it must be something that is changed in the new version.

The "Flight plan setting dialog" of EuroScope.
![image](https://user-images.githubusercontent.com/10661679/146946545-2e94d4c5-121c-405e-a63e-a0ae34d80bfa.png)

I acknowledge that there has been a change compared to the previous version. But as there was a major overhaul of up to 80% of the code/functionalities, it cannot be tracked as simple as you may expect. So I'm really depending on your contribution to provide some examples.

**Comment by erikwachters** [comment]
This is an example in sweatbox. The ADEP = ZBAA (outside sq1000). previous sector assigned 1000 and the flight squawks 1000, the MSSQ is shown and a discrete code is proposed if I click it.
For me the 1000 should be kept because the flight will not leave the sq1000 area again.
![FPL](https://user-images.githubusercontent.com/11937875/146949012-e410a8fa-be89-45de-8c79-b480e8096566.jpg)

**Comment by kusterjs** [comment]
Thanks for the example. That helps. Fully agree with you and will search the reason for the issue.

**Comment by kusterjs** [comment]
Can you check if the behaviour is fine with this version?
[CCAMS.zip](https://github.com/kusterjs/CCAMS/files/7756294/CCAMS.zip)

**Comment by erikwachters** [comment]
First test look good. Let me try it a couple of times online and I'll report back to you.

**Comment by erikwachters** [comment]
This version works perfectly as expected. I tested it a couple of times and I never had an unexpected behaviour.
