### ISSUE TITLE
LKAA airports code ranges

### ISSUE THREAD

**Issue by JKolol** [kusterjs/CCAMS#33]
Hi,

in vACC-CZ (LKAA) we use following squawk ranges:

LKPR: 1420 - 1447
LKAA (used by CTR for overflights without assigned squawk): 1450 - 1467
LKCV, LKKU, LKKV, LKMT, LKNA, LKPD and LKTB all share 1470 - 1477

Can you please add those to Airport code ranges?

Thank you

**Comment by kusterjs** [comment]
Configuration updated as requested

**Comment by JKolol** [comment]
Dear Jonas,

I'm sorry to bother you again, but after internal discussion in our vACC, we have decided to slightly change our squawk ranges. May I please ask you to increase squawk range for LKPR to 1457 (1420 - 1457)?

Thank you very much
