### ISSUE TITLE
Discrete code assigned when starting to track an aircraft (ES 3.2.3+)

### ISSUE THREAD

**Issue by erikwachters** [kusterjs/CCAMS#47]
Hi,

I'm not completely sure what exactly the problem is but one of the symptoms is that on assume of a traffic with SQ1000, the plugin assigns a discrete code at first, than if you click the lable field with CCAMS/Auto assign squawk, 1000 is assigned and the warning disappears.

I made a recording of the problem:
https://youtu.be/6dIR40Htask

Flight AFR37YN has code 1000 (which is correct for destination LFPG), after some seconds after assume gets 7107 assigned. After clicking the CCAMS/Auto assign squawk field, 1000 is assigned correctly and the warning is gone.

I hope this helps to start looking what the exact problem is.

Erik

**Comment by kusterjs** [comment]
Thanks for the report and the video, really appreciate the level of detail. I've already discussed the issue with Matisse (https://forum.vatsim.net/t/euroscope-v3-2-7/4308/29, plus further in chat) and I was of the opinion that this is a problem between the ES version and TopSky (see also https://vatsim-scandinavia.org/forums/topic/4551-new-es-323-icao-equipment-format/). But I'm not so sure anymore after your report.

I'll definitely have a look and do some tests with a debug version to narrow down the issue. Will update this issue then accordingly.

**Comment by erikwachters** [comment]
The only thing that changed on our setup is the EuroScope version from Beta R29 to 3.2.7. We use the same Topsky and CCAMS plugin versions as before the problem if that helps.

**Comment by MatisseBE** [comment]
Notably, we have been running this plugin combination of TS (v2.4.1) and CCAMS for many months without any issues. The only thing that recently changed is the ES-version.

**Comment by erikwachters** [comment]
Hi, any news on this topic? 
I was controlling last night during busy traffic an I had a lot of 1000 aircraft that received immidiately after assuming a discrete code. By clicking the CCAMS/Auto assign squawk field the 1000 was checked and retained. After 1h or so, all our normal discrete codes ran out and we got other random codes.
I think 3.2.7 changed so that plugins are running later in time. Maybe the problem can be solved by delaying the code check after assuming?

**Comment by kusterjs** [comment]
> Hi, any news on this topic? I was controlling last night during busy traffic an I had a lot of 1000 aircraft that received immidiately after assuming a discrete code. By clicking the CCAMS/Auto assign squawk field the 1000 was checked and retained. After 1h or so, all our normal discrete codes ran out and we got other random codes. I think 3.2.7 changed so that plugins are running later in time. Maybe the problem can be solved by delaying the code check after assuming?

I didn't find a solution yet, but delaying the check might actually be something I can try to implement and see if that helps.
Meanwhile can you set the plugin setting ´´acceptFPLformatICAO´´ to ´´0´´? This will result in only the FAA format of the flight plan being considered, which also might resolve the issue.

**Comment by erikwachters** [comment]
acceptFPLformatICAO to 0 doesn't do the trick...

**Comment by kusterjs** [comment]
Thanks for your feedback. I can't really test right now as the new version cannot be used live. But I can provide you a release with additional reporting/logging functionalities, which might provide me some clues about the source of the issue.

**Comment by erikwachters** [comment]
Yes please!

**Comment by MatisseBE** [comment]
@kusterjs I wouldn't mind running this version either :)

**Comment by kusterjs** [comment]
Thanks. Will get back to you with a slightly adpated version with better reporting.
As the stability of 3.2.9 seems ok for testing, I was already able to check the issue closer. It seems that the aircraft capabilities information provided to the plugin are no longer updated upon starting to track an aircraft. It is only updated later, which explains why the plugin will work by then.
I'm thinking about to release a version which has the automatic squawk update triggered by the start of an aircraft tracking disabled. This would remove some automatism, but avoid the unwanted assignments.
I have reported the issue now in the VATSIM forum and hope that this will soon be fixed.

**Comment by kusterjs** [comment]
The issue has been reported. However, there is currently no fix that I can provide within the plugin. Please deactivate the auto-assignment function while using the plugin with ES 3.2.3+.

**Comment by kusterjs** [comment]
EuroScope versions after 3.2.3 have an issue with the equipment codes provided to the plugin interface and there is currently no fix for this. This means version 3.2.4-3.2.9 are and will not be supported.
