### ISSUE TITLE
v2.4.0 error

### ISSUE THREAD

**Issue by erikwachters** [kusterjs/CCAMS#57]
Hi, I got the following error if I try to assign a sq via the TAG item 'CCAMS / Auto assign squawk'.
Also if I use TAG item 'CCAMS / Open SQUAWK assign popup' and select 'auto assign'.

![image](https://github.com/user-attachments/assets/3d31fbe2-a166-436c-91ee-dd8548aefebd)

**Comment by kusterjs** [comment]
Can you try again?

**Comment by kusterjs** [comment]
Server-side config issue, has been resolved
