### ISSUE TITLE
EDXX squawks not assigned

### ISSUE THREAD

**Issue by CedricMohler** [kusterjs/CCAMS#8]
The VATEUD squawk range for Germany is 2001 to 2577. In my understanding these should be assigned first, before other squawks are assigned. However the plugin assigns just random free squawks (that are correctly entered into the list of used squawks).

**Comment by kusterjs** [comment]
What controller call sign are you using?

**Comment by CedricMohler** [comment]
It doesn't seem to work for any of our stations, but we just tested it with EDDF_C_GND to make sure.

**Comment by kusterjs** [comment]
Seems to be because the VATEUD defined range is named EDXX, but there is no such FIR name. But the FIR name is relevant as soon as the departure airport ist known. Fixed it for now by adding EDGG, EDMM and EDWW to the list of FIR codes. Will check for a permanent fix in the code server-side.
